# Generated by Django 2.2.13 on 2021-07-01 21:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('rotation_period', models.CharField(blank=True, max_length=40)),
                ('orbital_period', models.CharField(blank=True, max_length=40)),
                ('diameter', models.CharField(blank=True, max_length=40)),
                ('climate', models.CharField(blank=True, max_length=40)),
                ('gravity', models.CharField(blank=True, max_length=40)),
                ('terrain', models.CharField(blank=True, max_length=40)),
                ('surface_water', models.CharField(blank=True, max_length=40)),
                ('population', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'planet',
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'producer',
            },
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=128)),
                ('height', models.CharField(blank=True, max_length=16)),
                ('mass', models.CharField(blank=True, max_length=16)),
                ('hair_color', models.CharField(blank=True, max_length=32)),
                ('skin_color', models.CharField(blank=True, max_length=32)),
                ('eye_color', models.CharField(blank=True, max_length=32)),
                ('birth_year', models.CharField(blank=True, max_length=16)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('hermaphrodite', 'Hermaphrodite'), ('n/a', 'N/A')], max_length=64)),
                ('home_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inhabitants', to='app.Planet')),
            ],
            options={
                'verbose_name_plural': 'people',
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('title', models.CharField(max_length=100)),
                ('episode_id', models.PositiveSmallIntegerField()),
                ('opening_crawl', models.TextField(max_length=1000)),
                ('release_date', models.DateField()),
                ('characters', models.ManyToManyField(blank=True, related_name='films', to='app.People')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='films', to='app.Director')),
                ('planets', models.ManyToManyField(blank=True, related_name='films', to='app.Planet')),
                ('producer', models.ManyToManyField(related_name='films', to='app.Producer')),
            ],
            options={
                'db_table': 'film',
            },
        ),
    ]
